version: "3"
services:
  #docker快速启动redis
  lesson-cloud-redis:
    container_name: redis-dev
    image: redis:5
    ports: 
      - 6379:6379
    volumes:
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
    command: 
      redis-server
    restart: always

  #docker快速启动rabbitmq
  lesson-cloud-rabbitmq:
    container_name: rabbitmq-dev
    build: ./rabbitmq/
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
      - "15671:15671"
      - "15672:15672"
    


